const authRouter = require('./route.authentication')
const userRouter = require('./route.user')
const loginRouter = require('./route.login')
const reportRouter = require('./route.report')
const surveyRouter = require('./route.survey')
const companyRouter = require('./route.company')
const buildingRouter = require('./route.building')
const commentRouter = require('./route.comment')
const formRouter = require('./route.form')
const answerCountRouter = require('./route.answerCount')
const express = require('express')
const { routeMiddleware } = require('../middleware/middleware.authorization')
const router = express.Router()

router.use('/login', loginRouter)
router.use('/user', userRouter)
router.use(routeMiddleware)

router.use('/auth', authRouter)
router.use('/survey', surveyRouter)
// router.use('/user', userRouter)
router.use('/count', answerCountRouter)
router.use('/company', companyRouter)
router.use('/building', buildingRouter)
router.use('/comment', commentRouter)
router.use('/formInfo', formRouter)

module.exports = router
